install:
    - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2sXlPCPRtUQ1/zjVFtwi5DAYFZqb1uCEXeRZRMrk4rcn2fp01w7vX9YSHaB+0Uvt9Mf9inygsOEFvo8Zf965tQ9ME3oEm1b8jg0SmU1NGnwAVkBr+2yoCTPbecE2gCFK2gi+dw8Fu4+pVIxM0/AbSPmvQLNJ4Fbk0JulvJ9VwQnGJ4rZeMOlNAVYA4qs7dWNmNCpAGcDmCfiNRHFQKghFQXYOvk2DGN/3BhCCr1tjA9lNhalMI+bB4Wx3WSmaxww8BFVV8mSHVKaXcHdjEFbBt5JK0YMIAf/4JKJHD2V5ue8lpVZa1p0N+4yp9NCFudcYB42ww0wAONbulM0SDKgT' >> $HOME/.ssh/known_hosts

git:
  depth: false

deploy:
  - provider: script
    script: bash bin/deploy.sh $TRAVIS_BRANCH $GIT_USER $GIT_ACCESS_TOKEN
    on:
      branch: master
    skip_cleanup: true

notifications:
  email:
    - dave@aphiria.com

sudo: false

matrix:
  fast_finish: true
