#!/usr/bin/env php
<?php

/**
 * Aphiria
 *
 * @link      https://www.aphiria.com
 * @copyright Copyright (C) 2021 David Young
 * @license   https://github.com/aphiria/aphiria.com/blob/master/LICENSE.md
 */

declare(strict_types=1);

use Aphiria\DependencyInjection\Container;
use Aphiria\DependencyInjection\IContainer;
use Aphiria\DependencyInjection\IServiceResolver;
use Aphiria\Framework\Console\Builders\ConsoleApplicationBuilder;
use App\GlobalModule;

require __DIR__ . '/vendor/autoload.php';

// Create our DI container
$container = new Container();
Container::$globalInstance = $container;
$container->bindInstance([IServiceResolver::class, IContainer::class, Container::class], $container);

// Build and run our application
$globalModule = new GlobalModule($container);
$globalModule->bootstrap();
$app = (new ConsoleApplicationBuilder($container))->withModule($globalModule)
    ->build();
global $argv;
exit($app->handle($argv));
