services:
  nginx:
    ports:
      - 8080:8080
      - 80:80
    volumes: # Set up some bind mounts to simplify local development
      - ./:/var/www/api
      - ./public-web:/var/www/web/public-web
      - ./docker/nginx/templates:/etc/nginx/templates
  php:
    volumes: # Set up some bind mounts to simplify local development
      - ./:/var/www/api
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
