version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: registry.digitalocean.com/aphiria-dot-com/aphiria/nginx:latest
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    networks:
      - aphiria.com
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    image: registry.digitalocean.com/aphiria-dot-com/aphiria/php:latest
    restart: unless-stopped
    tty: true
    working_dir: /var/www/api
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - aphiria.com
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - aphiria.com

# TODO: Do I still need this?
networks:
  aphiria.com:
    driver: bridge

volumes:
  db:
    driver: local
