name: aphiria-com-infrastructure
runtime:
  name: nodejs
  options:
    typescript: true
description: Aphiria.com infrastructure - shared components and stacks for local, preview, and production

config:
  namespace:
    value:
      imagePullSecret:
        registry: "ghcr.io"

  cluster:
    value:
      name: "aphiria-com-cluster"
      region: "nyc3"
      version: "1.34.1-do.2"
      autoUpgrade: true
      surgeUpgrade: false
      ha: false
      nodeSize: "s-2vcpu-2gb"
      nodeCount: 1
      autoScale: true
      minNodes: 1
      maxNodes: 4
      vpcUuid: "976f980d-dc84-11e8-80bc-3cfdfea9fba1"

  app:
    value:
      imagePullPolicy: "IfNotPresent"
      web:
        url: "https://www.aphiria.com"
        cookieDomain: ".aphiria.com"
        replicas: 2
        image: "ghcr.io/aphiria/aphiria.com-web:latest"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        podDisruptionBudget:
          minAvailable: 1
      api:
        url: "https://api.aphiria.com"
        logLevel: "warning"
        replicas: 2
        image: "ghcr.io/aphiria/aphiria.com-api:latest"
        resources:
          initContainer:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          nginx:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          php:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        podDisruptionBudget:
          minAvailable: 1
      migration:
        resources:
          migration:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          initContainer:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"

  postgresql:
    value:
      version: "16"
      persistentStorage: true
      storageSize: "20Gi"
      useHostPath: false
      host: "db.default.svc.cluster.local"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"

  gateway:
    value:
      tlsMode: "letsencrypt-prod"
      domains:
        - "aphiria.com"
        - "*.aphiria.com"
      requireRootAndWildcard: true
      dns:
        domain: "aphiria.com"
        records:
          - name: "@"
            resourceName: "production-root-dns"
          - name: "www"
            resourceName: "production-www-dns"
          - name: "api"
            resourceName: "production-api-dns"
          - name: "grafana"
            resourceName: "production-grafana-dns"
        ttl: 300

  monitoring:
    value:
      namespace:
        resourceQuota:
          cpu: "4"
          memory: "16Gi"
          pods: "30"

  prometheus:
    value:
      scrapeInterval: "15s"
      storageSize: "10Gi"
      retentionTime: "7d"
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      operator:
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        configReloader:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
      nodeExporter:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      kubeStateMetrics:
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"

  grafana:
    value:
      version: "11.0.0"
      defaultReceiver: "email-admin"
      ingressSectionName: "https-subdomains"
      storageSize: "5Gi"
      hostname: "grafana.aphiria.com"
      replicas: 1
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"
      githubOrg: "aphiria"
      adminUser: "davidbyoung"
