environment:
  - aphiria.com/Preview

config:
  # Kubernetes cluster configuration
  cluster:
    name: "aphiria-com-preview-cluster"
    region: "nyc3"
    version: "1.34.1-do.2"
    autoUpgrade: true
    surgeUpgrade: false
    ha: false
    nodeSize: "s-2vcpu-2gb"
    nodeCount: 1
    autoScale: true
    minNodes: 1
    maxNodes: 4
    vpcUuid: "976f980d-dc84-11e8-80bc-3cfdfea9fba1"

  # Gateway configuration
  gateway:
    domains:
      - "*.pr.aphiria.com"
      - "*.pr-api.aphiria.com"
      - "pr-grafana.aphiria.com"
    requireRootAndWildcard: false # Preview doesn't need root listener
    dns:
      records:
        - name: "*.pr"
          resourceName: "preview-web-dns"
        - name: "*.pr-api"
          resourceName: "preview-api-dns"
        - name: "pr-grafana"
          resourceName: "preview-grafana-dns"

  # Prometheus monitoring
  prometheus:
    retentionTime: "14d"
    resources:
      limits:
        cpu: "1000m" # Higher limit for preview

  # Grafana monitoring (preview-specific settings)
  grafana:
    defaultReceiver: "local-notifications" # No email for preview
    ingressSectionName: "https-root" # Preview uses exact match
    hostname: "pr-grafana.aphiria.com"
    resources:
      requests:
        memory: "512Mi" # More memory for preview
      limits:
        cpu: "500m" # Higher CPU limit for preview
        memory: "1Gi"
