environment:
  - aphiria.com/Preview

config:
  # Static values shared by all preview-PR stacks
  aphiria-com-infrastructure:baseStackReference: "davidbyoung/aphiria-com-infrastructure/preview-base"
  aphiria-com-infrastructure:skipBaseInfrastructure: true

  # Preview PR-specific overrides (static defaults only, dynamic values set by workflow)
  aphiria-com-infrastructure:overrides:
    app:
      imagePullPolicy: "Always"
      web:
        cookieDomain: ".pr.aphiria.com"
        replicas: 1
      api:
        logLevel: "debug"
        replicas: 1
    postgresql:
      createDatabase: true
    namespace:
      resourceQuota:
        cpu: "2"
        memory: "4Gi"
        pods: "5"
      # Network policies allow preview-pr pods to communicate with shared services in preview-base
      # (PostgreSQL in default namespace, DNS, and external HTTPS for API calls)
      networkPolicy:
        allowDNS: true
        allowHTTPS: true
        allowPostgreSQL:
          host: "db.default.svc.cluster.local"
          port: 5432
