config:
  aphiria-com-infrastructure:webImage: davidbyoung/aphiria.com-web:8e1ebfd326d7d20aea7104f1269cb1a9ce325d69-a9b9031929d39f8dd4863bec41bbe5b76cb2b555
  aphiria-com-infrastructure:apiImage: nginx:alpine
  aphiria-com-infrastructure:dbPassword:
    secure: AAABAMibEeQWLzxWL7dXyDpei38yC2lO73XwghhUaqkNQaJSznUrAvqvDhwNQnt3PyVywGJJB1Qi8X7tEHTByw==
  digitalocean:token:
    secure: AAABADa3IC83V2trAb1RJHWlIfKuFk0a0UGA81FZytH30/j+5WSIGxzYJhbPOKl65Zen75bOxCB1Ax6iLjNrzmRHgVxx2LWhozo/rerm/7J4F+nY41EJb9Y1+vodgHaMPh+tW3gKGg==
