environment:
  - aphiria.com/Production

config:
  # Production cluster configuration
  cluster:
    value:
      name: "aphiria-com-cluster"
      region: "nyc3"
      version: "1.34.1-do.2"
      autoUpgrade: true
      surgeUpgrade: false
      ha: false
      nodeSize: "s-2vcpu-2gb"
      nodeCount: 2
      autoScale: true
      minNodes: 2
      maxNodes: 4
      vpcUuid: "976f980d-dc84-11e8-80bc-3cfdfea9fba1"

  # Production namespace configuration (for image pull secrets)
  namespace:
    value:
      imagePullSecret:
        registry: "ghcr.io"

  # Production-specific overrides
  aphiria-com-infrastructure:overrides:
    gateway:
      dns:
        domain: "aphiria.com"
        records:
          - name: "@"
            resourceName: "production-root-dns"
          - name: "www"
            resourceName: "production-www-dns"
          - name: "api"
            resourceName: "production-api-dns"
          - name: "grafana"
            resourceName: "production-grafana-dns"
        ttl: 300
