environment:
  - aphiria.com/Production

config:
  # Kubernetes cluster configuration
  cluster:
    name: "aphiria-com-cluster"
    region: "nyc3"
    version: "1.34.1-do.2"
    autoUpgrade: true
    surgeUpgrade: false
    ha: false
    nodeSize: "s-2vcpu-2gb"
    nodeCount: 1
    autoScale: true
    minNodes: 1
    maxNodes: 4
    vpcUuid: "976f980d-dc84-11e8-80bc-3cfdfea9fba1"
