environment:
  - aphiria.com/Preview

config:
  # Set dynamically by CD workflow during deployment
  aphiria-com-infrastructure:prNumber: 123
  aphiria-com-infrastructure:baseStackReference: "organization/aphiria-com-infrastructure/preview-base"
  aphiria-com-infrastructure:skipBaseInfrastructure: true

  # Preview PR-specific overrides
  aphiria-com-infrastructure:overrides:
    app:
      imagePullPolicy: "Always"
      web:
        # Set dynamically by CD workflow during deployment
        url: "https://123.pr.aphiria.com"
        cookieDomain: ".pr.aphiria.com"
        replicas: 1
        # Set dynamically by CD workflow during deployment (with digest)
        image: "ghcr.io/aphiria/aphiria.com-web@sha256:abc123..."
      api:
        # Set dynamically by CD workflow during deployment
        url: "https://123.pr-api.aphiria.com"
        logLevel: "debug"
        replicas: 1
        # Set dynamically by CD workflow during deployment (with digest)
        image: "ghcr.io/aphiria/aphiria.com-api@sha256:def456..."
    postgresql:
      createDatabase: true
      # Set dynamically by CD workflow during deployment
      databaseName: "aphiria_pr_123"
    namespace:
      # Set dynamically by CD workflow during deployment
      name: "preview-pr-123"
      resourceQuota:
        cpu: "2"
        memory: "4Gi"
        pods: "5"
      # Network policies allow preview-pr pods to communicate with shared services in preview-base
      # (PostgreSQL in default namespace, DNS, and external HTTPS for API calls)
      networkPolicy:
        allowDNS: true
        allowHTTPS: true
        allowPostgreSQL:
          host: "db.default.svc.cluster.local"
          port: 5432
