environment:
  - aphiria.com/Preview-Base

config:
  # Preview base-specific overrides
  aphiria-com-infrastructure:overrides:
    cluster:
      name: "aphiria-com-preview-cluster"
    gateway:
      domains:
        - "*.pr.aphiria.com"
        - "*.pr-api.aphiria.com"
        - "pr-grafana.aphiria.com"
      requireRootAndWildcard: false
      dns:
        domain: "aphiria.com"
        records:
          - name: "*.pr"
            resourceName: "preview-web-dns"
          - name: "*.pr-api"
            resourceName: "preview-api-dns"
          - name: "pr-grafana"
            resourceName: "preview-grafana-dns"
        ttl: 300
    prometheus:
      resources:
        limits:
          cpu: "1000m"
    grafana:
      hostname: "pr-grafana.aphiria.com"
      defaultReceiver: "local-notifications"
      ingressSectionName: "https-root"
      resources:
        requests:
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
