environment:
  - aphiria.com/Preview

config:
  cluster:
    value:
      name: "aphiria-com-preview-cluster"
      region: "nyc3"
      version: "1.34.1-do.2"
      autoUpgrade: true
      surgeUpgrade: false
      ha: false
      nodeSize: "s-2vcpu-2gb"
      nodeCount: 2
      autoScale: true
      minNodes: 2
      maxNodes: 4
      vpcUuid: "976f980d-dc84-11e8-80bc-3cfdfea9fba1"

  # Preview base-specific overrides
  aphiria-com-infrastructure:overrides:
    gateway:
      domains:
        - "*.pr.aphiria.com"
        - "*.pr-api.aphiria.com"
        - "pr-grafana.aphiria.com"
      requireRootAndWildcard: false
      dns:
        domain: "aphiria.com"
        records:
          - name: "*.pr"
            resourceName: "preview-web-dns"
          - name: "*.pr-api"
            resourceName: "preview-api-dns"
          - name: "pr-grafana"
            resourceName: "preview-grafana-dns"
        ttl: 300
    prometheus:
      resources:
        limits:
          cpu: "1000m"
    grafana:
      hostname: "pr-grafana.aphiria.com"
      defaultReceiver: "local-notifications"
      ingressSectionName: "https-root"
      resources:
        requests:
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
