environment:
  - aphiria.com/Preview-Base

config:
  # Preview base-specific overrides
  aphiria-com-infrastructure:overrides:
    app:
      web:
        env:
          # Preview URLs are dynamic per PR: pr-123.pr.aphiria.com
          # API_URI will be interpolated in the stack code
          COOKIE_DOMAIN: .pr.aphiria.com
          NODE_ENV: production
    cluster:
      name: aphiria-com-preview-cluster
      minNodes: 1
    gateway:
      domains:
        - "*.pr.aphiria.com"
        - "*.pr-api.aphiria.com"
        - pr-grafana.aphiria.com
      requireRootAndWildcard: false
      dns:
        domain: aphiria.com
        records:
          - name: "*.pr"
            resourceName: preview-web-dns
          - name: "*.pr-api"
            resourceName: preview-api-dns
          - name: pr-grafana
            resourceName: preview-grafana-dns
        ttl: 300
    grafana:
      hostname: pr-grafana.aphiria.com
      defaultReceiver: grafana-default-email # Grafana's built-in no-op receiver (UI only, no emails)
      ingressSectionName: https-root
