# Note: This is a dev config that should not be used in production.  It will be overwritten for production during CI/CD.
apiVersion: v1
kind: Secret
metadata:
  name: env-var-secrets
stringData:
  DB_USER: "testuser"
  DB_PASSWORD: "testpassword"
