apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      # Copy the PHP source code into a shared volume that is mounted to PHP-FPM and nginx
      initContainers:
        - name: copy-api-code
          image: davidbyoung/aphiria.com-api:latest
          imagePullPolicy: Always
          # We copy and preserve the permissions so that nginx has access to things like the tmp directory
          command: [ 'sh', '-c', 'cp -Rp /app/api/. /usr/share/nginx/html' ]
          volumeMounts:
            - name: api-code
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: api-code
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: php
          image: davidbyoung/aphiria.com-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: env-var-secrets
            - configMapRef:
                name: env-vars
          volumeMounts:
            - name: api-code
              mountPath: /usr/share/nginx/html
      volumes:
        - name: api-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
