apiVersion: v1
kind: Service
metadata:
  name: api
  labels: # We need labels to be able to scrape metrics for Prometheus
    app: api
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 80
    - name: fastcgi
      protocol: TCP
      port: 9000
      targetPort: 9000
