apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  cpu-usage-alert.yaml: |-
    apiVersion: 1
    groups:
      - name: "CPU Usage Alerts"
        interval: 1m
        rules:
          - uid: cpu-usage-alert
            title: "High CPU Usage"
            condition: A > 90
            data:
              A:
                refId: A
                expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                datasourceUid: prometheus
            labels:
              severity: critical
