apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  namespaceSelector:
    matchNames:
      - nginx-gateway
  endpoints:
    - port: metrics
      interval: 30s
