apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  namespaceSelector:
    matchNames:
      - nginx-gateway
  endpoints:
    - port: metrics
      interval: 30s

---

# Expose the metrics port for scraping by Prometheus
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/name: nginx-gateway-fabric
spec:
  selector:
    app.kubernetes.io/name: nginx-gateway-fabric
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
