version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    env_file: # TODO: REMOVE!!!!!!!!!!
      - ./../.env
    ports:
      - ${NGINX_API_PORT}
      - ${NGINX_WEB_PORT}
      - 443
    volumes:
      - ./..:/var/www/api
      - ./../public-web:/var/www/web/public-web
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/api
    ports:
      - 9000:9000
    volumes:
      - ./..:/var/www/api
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  db:
    image: postgres:11.10-alpine
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db:
    driver: local
