version: '3'
services:
  nginx:
    build:
      context: ./..
      dockerfile: ./docker/nginx/Dockerfile
    image: aphiria/nginx:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./../.env
    networks:
      - aphiria.com
    depends_on:
      - php
  php:
    build:
      context: ./..
      dockerfile: ./docker/php/Dockerfile
    image: aphiria/php:latest
    restart: unless-stopped
    tty: true
    working_dir: /var/www/api
    env_file:
      - ./../.env
    ports:
      - 9000:9000
    networks:
      - aphiria.com
    depends_on:
      - db
  db:
    image: postgres:11.10-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./../.env
    networks:
      - aphiria.com

networks:
  aphiria.com:
    driver: bridge

volumes:
  db:
    driver: local
