apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: davidbyoung/aphiria.com-web:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: js-config
              mountPath: /usr/share/nginx/html/js/config
          livenessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
      volumes:
        - name: js-config
          configMap:
            name: js-config
