apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api/config-maps.yml
  - ./api/deployments.yml
  - ./api/services.yml
  - ./core/config-maps.yml
  - ./database/deployments.yml
  - ./database/jobs.yml
  - ./database/persistent-volumes.yml
  - ./database/services.yml
  - ./gateway-api/gateway.yml
  - ./gateway-api/http-routes.yml
  - ./gateway-api/namespace.yml
  - ./monitoring/namespace.yml
  - ./monitoring/notifications.yml
  - ./monitoring/service-monitor.yml
  - ./redis/default-secrets.yml
  - ./redis/monitoring-secrets.yml
  - ./web/config-maps.yml
  - ./web/deployments.yml
  - ./web/services.yml
