apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
  - ./api/config-maps.yml
  - ./api/deployments.yml
  - ./api/services.yml
  - ./core/config-maps.yml
  - ./database/deployments.yml
  - ./database/jobs.yml
  - ./database/persistent-volumes.yml
  - ./database/services.yml
  - ./gateway-api/gateway.yml
  - ./gateway-api/http-routes.yml
  - ./web/config-maps.yml
  - ./web/deployments.yml
  - ./web/services.yml
