/**
 * Doc page metadata
 *
 * Matches the structure from dist/docs/meta.json generated by tools/build-docs
 */
export interface DocPage {
    /** Version identifier (e.g., "1.x", "2.x") */
    version: string;

    /** URL-friendly slug (e.g., "installation", "routing") */
    slug: string;

    /** Human-readable page title (e.g., "Installation", "Routing") */
    title: string;
}
