# TODOS
# - Can/should I set the domains to something like api.aphiria.local and aphiria.local, and swap in the prod values when deploying?  What's SOP?
# - Am I actually hitting my local k8s cluster when currently hitting aphiria.com?
# - Update README.md


# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    app: secrets
data:
  DB_HOST: "dGVzdC1ob3N0Cg==" # TODO:  Store this as a secret in GitHub
  DB_USER: "dGVzdC11c2VyCg==" # TODO:  Store this as a secret in GitHub
  DB_PASSWORD: "dGVzdC1wYXNzd29yZAo=" # TODO:  Store this as a secret in GitHub
  DB_PORT: "NTQzMgo=" # TODO:  Store this as a secret in GitHub
  DB_NAME: "ZGVmYXVsdGRiCg==" # TODO:  Store this as a secret in GitHub

---
# Web deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: aphiria-com-web
          image: aphiria.com-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
# Web service
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# DB service
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: db

---
# DB persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data

---
# DB persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
# DB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          env:
          # These specific env vars are required for PostgreSQL to start up
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: DB_PASSWORD
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pv-claim

---
# Ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.aphiria.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aphiria-com-api
                port:
                  number: 8000
    - host: aphiria.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aphiria-com-web
                port:
                  number: 80

---
# API service
apiVersion: v1
kind: Service
metadata:
  name: aphiria-com-api
spec:
  selector:
    app: aphiria-com-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# API code volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# API deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aphiria-com-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aphiria-com-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aphiria-com-api
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-code
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: php
          image: aphiria.com-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: secrets
          volumeMounts:
            - name: shared-code
              mountPath: /var/www/html
      volumes:
        - name: shared-code
          persistentVolumeClaim:
            claimName: api-code-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf

---
# nginx config to serve PHP files
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /usr/share/nginx/html;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass php:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
