apiVersion: v1
kind: Secret
metadata:
  namespace: aphiria.com
  name: secret
type: Opaque
data:
  db-user: TODO # Need to actually secure these secrets
  db-password: TODO # Need to actually secure these secrets
