apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
  - ./core/secrets.yml
  - ./gateway-api/certificates.yml
  - ./monitoring/secrets.yml
patches:
  # Update the images to be local for easier testing
  - target:
      name: api
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/image
        value: aphiria.com-api:latest
      - op: replace
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: /spec/template/spec/containers/1/image
        value: aphiria.com-api:latest
      - op: replace
        path: /spec/template/spec/containers/1/imagePullPolicy
        value: IfNotPresent
  - target:
      name: db-migration
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: aphiria.com-api:latest
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      name: web
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: aphiria.com-web:latest
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  # Update dev to use local TLS secrets
  - target:
      name: nginx-gateway
      namespace: nginx-gateway
      kind: Gateway
    patch: |-
      - op: replace
        path: /spec/listeners/2/tls/certificateRefs/0/name
        value: tls-secret
      - op: replace
        path: /spec/listeners/3/tls/certificateRefs/0/name
        value: tls-secret
