import { readFileSync } from "fs";
import { join } from "path";
import { DocumentationPage } from "@/types/documentation";

/**
 * Read documentation metadata from compiled artifacts
 *
 * Reads from dist/docs/meta.json generated by tools/build-docs during Docker build
 */
export function readDocumentationMeta(): DocumentationPage[] {
    const metaPath = join(process.cwd(), "dist/docs/meta.json");

    try {
        const content = readFileSync(metaPath, "utf8");
        return JSON.parse(content) as DocumentationPage[];
    } catch (error) {
        console.error("Failed to read documentation metadata:", error);
        return [];
    }
}

/**
 * Read rendered HTML for a specific documentation page
 *
 * @param slug - Page slug (e.g., "installation")
 * @returns HTML content or null if not found
 */
export function readDocumentationHtml(slug: string): string | null {
    const htmlPath = join(process.cwd(), "dist/docs/rendered", `${slug}.html`);

    try {
        return readFileSync(htmlPath, "utf8");
    } catch (error) {
        console.error(`Failed to read documentation HTML for ${slug}:`, error);
        return null;
    }
}

/**
 * Get all documentation pages for a specific version
 *
 * @param version - Version identifier (e.g., "1.x")
 * @returns Array of documentation pages
 */
export function getDocumentationForVersion(version: string): DocumentationPage[] {
    const allDocs = readDocumentationMeta();
    return allDocs.filter((doc) => doc.version === version);
}
