# Self-signed certificate cluster issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: nginx-gateway
spec:
  selfSigned: {}

---
# Self-signed certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-crt
  namespace: nginx-gateway
spec:
  secretName: tls-secret
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer
  commonName: "*.aphiria.com"
  isCA: true
  dnsNames:
    - www.aphiria.com
    - api.aphiria.com
