# Self-signed certificate cluster issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: nginx-gateway
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@aphiria.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-secrets
              key: DIGITALOCEAN_ACCESS_TOKEN
