# Use a LetsEncrypt TLS certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: nginx-gateway
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # TODO: Need to update this to use the prod URL once I'm done testing everything
    email: admin@aphiria.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-secrets
              key: DIGITALOCEAN_ACCESS_TOKEN
