name: build-docker-image
on:
  workflow_call:
    inputs:
      dockerfile:
        description: The path to the Dockerfile
        required: true
        type: string
      image:
        description: The name of the image
        required: true
        type: string
      image-sha-artifact-name:
        description: The name of the artifact that we upload that contains the Docker image SHA
        required: true
        type: string
    secrets:
      DOCKER_ACCESS_TOKEN:
        description: The Docker access token
        required: true
jobs:
  build-image:
    runs-on: ubuntu-latest
    name: ${{ inputs.image }}
    outputs:
      image_sha: ${{ steps.get-sha.outputs.image_sha }}
      docs_sha: ${{ steps.get-sha.outputs.docs_sha }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Out Docs
        uses: actions/checkout@v4
        with:
          repository: aphiria/docs
          path: docs
      - name: Get SHA
        id: get-sha
        run: |
          code_sha=$(git rev-parse HEAD)
          echo "Latest code SHA: $code_sha"

          cd docs
          docs_sha=$(git rev-parse HEAD)
          echo "Latest docs SHA: $docs_sha"
          cd ..

          image_sha="${code_sha}-${docs_sha}"

          # Store the SHAs for use in other steps in this job
          echo "docs_sha=$docs_sha" >> $GITHUB_OUTPUT
          echo "image_sha=$image_sha" >> $GITHUB_OUTPUT

          # Store the SHA so that we can retrieve it from other workflows (GitHub Actions does not support outputs from templated workflows into other jobs)
          echo $image_sha > image_sha.txt
      - name: Upload SHA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image-sha-artifact-name }}
          path: image_sha.txt
      - name: Log Into Docker Hub
        uses: docker/login-action@v3
        with:
          username: davidbyoung
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set Up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.image }}:${{ steps.get-sha.outputs.image_sha }}
          cache-from: type=registry,ref=${{ inputs.image }}:buildcache
          cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
          build-args: |
            # Force the documentation to get rebuilt if it has changed since the image was built
            IMAGE_SHA=${{ steps.get-sha.outputs.image_sha }}
            DOCS_SHA=${{ steps.get-sha.outputs.docs_sha }}
