name: build-docker-image
on:
  workflow_call:
    inputs:
      dockerfile:
        description: The path to the Dockerfile
        required: true
        type: string
      image:
        description: The name of the image
        required: true
        type: string
    secrets:
      DOCKER_ACCESS_TOKEN:
        description: The Docker access token
        required: true
jobs:
  build-image:
    runs-on: ubuntu-latest
    name: ${{ inputs.image }}
    outputs:
      code_sha: ${{ steps.get-code-sha.outputs.sha }}
      docs_sha: ${{ steps.get-docs-sha.outputs.sha }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Code SHA
        id: get-code-sha
        run: |
          sha=$(git rev-parse HEAD)
          echo "Latest commit SHA: $sha"
          echo "::set-output name=sha::$sha"
      - name: Check Out Docs
        uses: actions/checkout@v4
        with:
          repository: aphiria/docs
          path: docs
      - name: Get Docs SHA
        id: get-docs-sha
        run: |
          cd docs
          sha=$(git rev-parse HEAD)
          echo "Latest commit SHA: $sha"
          echo "::set-output name=sha::$sha"
      - name: Log Into Docker Hub
        uses: docker/login-action@v3
        with:
          username: davidbyoung
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set Up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.image }}:${{ steps.get-code-sha.outputs.sha }}-${{ steps.get-docs-sha.outputs.sha }}
          cache-from: type=registry,ref=${{ inputs.image }}:buildcache
          cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
          build-args: |
            CACHE_BUST=${{ github.run_number }}
