name: ci
on: # TODO: How do I only run the 'deploy' job in master?
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]
    name: 'Build PHP ${{ matrix.php }} - ${{ matrix.stability }}'
    env:
      # Set these so that views are compiled with correct links
      APP_WEB_URL: https://www.aphiria.com
      APP_API_URL: https://api.aphiria.com
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, libxml, mbstring, pcntl, zip
          tools: composer:v2
      - name: Install Composer Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Optimize Autload
        run: composer dump-autoload -o
      - name: Run Unit Tests
        run: vendor/bin/phpunit --testsuite Unit --verbose
      - name: Run Linter
        run: composer phpcs-test
      - name: Run Psalm Static Analysis
        run: composer psalm
      - name: Build Gulp
        run: yarn install && yarn global add gulp && gulp build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ '8.0' ]
        stability: [ prefer-stable ]
    name: 'Deploy PHP ${{ matrix.php }} - ${{ matrix.stability }}'
    steps:
      # TODO: Need to figure out how to run docker-compose with prod YAML config and .env
      # TODO: Run integration tests inside of container
      # TODO: Do I need to seed DB here in CI to have meaningful integration tests?
      - name: Publish Nginx Image to GitHub Packages Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          dockerfile: ./../../docker/nginx/Dockerfile
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: aphiria/nginx:latest
      - name: Publish PHP Image to GitHub Packages Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          dockerfile: ./../../docker/php/Dockerfile
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: aphiria/php:latest
      # TODO: Need to actually get these containers to Digital Ocean
