# TODO: Need to remove bin directory and .travis.yml
# TODO: Need to figure out a way to prevent secrets from showing up in build logs from .env
name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']
        stability: [prefer-stable]
    name: Build Website
    env:
      # Set these so that views are compiled with correct links
      APP_WEB_URL: https://www.aphiria.com
      APP_API_URL: https://api.aphiria.com
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, libxml, mbstring, pcntl, zip
          tools: composer:v2
      - name: Install Composer Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Optimize Autload
        run: composer dump-autoload -o
      - name: Run Unit Tests
        run: vendor/bin/phpunit --testsuite Unit --verbose
      - name: Run Linter
        run: composer phpcs-test
      - name: Run Psalm Static Analysis
        run: composer psalm
      - name: Build Gulp
        run: yarn install && yarn global add gulp && gulp build
# TODO - Potentially re-add the deploy job and the steps below
#      - name: Upload Build Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: build
#          path: |
#            .
#            !./.git
#            !./node_modules
#  deploy:
    #if: github.ref == 'refs/heads/master' TODO: Need to re-enable this once I merge my PR in and work out all the other issues
    # TODO: See if we can use a cache so we're not having to rebuild the entire image every single run.  https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei
#    needs: [build]
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        php: [ '8.0' ]
#        stability: [ prefer-stable ]
#    name: Deploy Website
#    steps:
#      - name: Download Build Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: build
      - name: Copy .env File
        run: |
          touch .env
          echo ${{ secrets.APHIRIA_DOT_COM_DOT_ENV }} >> .env
          cat .env
      - name: Build Docker Images
        run: docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.dev.yml up -d # TODO: Switch this to docker-compose.prod.yml once we've worked out kinks
      - name: Check Docker Status # TODO: Remove this step once I've figured out the networking issue
        run: docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.dev.yml status
      - name: Build Documentation Search Index
        run: docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.dev.yml exec -T php php aphiria docs:index # TODO: Switch this to docker-compose.prod.yml once we've worked out kinks
      - name: Run integration tests
        run: docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.dev.yml exec -T php vendor/bin/phpunit --testsuite Integration --configuration phpunit.xml.dist --verbose # TODO: Switch this to docker-compose.prod.yml once we've
      - name: Publish Nginx Image to GitHub Packages Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: aphiria/aphiria.com/aphiria/nginx:latest
          tag_with_ref: true
      - name: Publish PHP Image to GitHub Packages Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: aphiria/aphiria.com/aphiria/php:latest
          tag_with_ref: true
      # TODO: Need to actually get these containers to Digital Ocean
